### ISSUE TITLE
Failing Test

### ISSUE THREAD

**Issue by zph** [toumorokoshi/tome#52]
Hello again!

I've been working on patches to automate the building of this on Github Actions across multiple architectures and platforms (ie aarch64 and x86_64 on both Linux and Mac).

During that I discovered that my own version of it is failing one specific test and I was surprised because I thought that's part of the CI baked into your repo.

Reporting it here in case this is not yet known.

PS - I've been happily using this for my team for the past 12 months and it's been a great help :). I have a few features I'd like to suggest and if time allows, build them and contribute upstream.

More important than fixing the test is also fixing any CI issue that allowed it to get into the codebase un-flagged.

Test error output:

```
> cargo test
running 29 tests
test commands::tests::test_should_source ... ok
test commands::tests::test_should_not_source ... ok
test commands::tests::test_usage ... ok
test commands::tests::test_help ... ok
test lib_tests::test_script_directory_argument ... ok
test lib_tests::test_directory_completion ... ok
test lib_tests::test_root_directory_completion ... ok
test lib_tests::test_exec_simple_script ... ok
test lib_tests::test_exec_recursive_simple_script ... ok
test lib_tests::test_script_in_directory_not_found ... ok
test lib_tests::test_dangerous_characters_quoted ... ok
test lib_tests::test_simple_script ... ok
test lib_tests::test_script_in_directory ... ok
test lib_tests::test_simple_script_with_args ... ok
test lib_tests::test_source ... ok
test lib_tests::test_simple_script_no_completion ... ok
test shell_type_tests::test_shell_type::case_1_bash ... ok
test shell_type_tests::test_shell_type::case_2_bin_bash ... ok
test lib_tests::test_tome_completion ... ok
test shell_type_tests::test_shell_type::case_3_zsh ... ok
test shell_type_tests::test_shell_type::case_4_bin_zsh ... ok
test shell_type_tests::test_shell_type::case_5_fish ... ok
test lib_tests::test_use_arg ... ok
test lib_tests::test_execute_help ... ok
test lib_tests::test_execute_commands ... ok
test lib_tests::test_help_page ... ok
test lib_tests::test_help_page_when_execute_no_args ... ok
test lib_tests::test_simple_script_completion ... FAILED
test lib_tests::test_source_completion ... ok

failures:

---- lib_tests::test_simple_script_completion stdout ----
thread 'lib_tests::test_simple_script_completion' panicked at 'assertion failed: `(left == right)`
  left: `Ok("")`,
 right: `Ok("file autocomplete example")`', src/lib_tests.rs:87:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    lib_tests::test_simple_script_completion

test result: FAILED. 28 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--lib`
```

No rush on this, I'll take a look as time allows.

Thanks!

**Comment by toumorokoshi** [comment]
Hi! Very strange, yes we should pass all tests and CI does check for that.

Must be something environment specific - I'll take a look today or tomorrow.

**Comment by zph** [comment]
Adding more background:

Failing on my mac when run under fish and bash shell. Could be something environmental.

Head of output:
```
bash-5.2$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running unittests src/lib.rs (target/debug/deps/tome-ca586cb57dc09330)
```

Here's the failed run on Linux aarch64 on rust stable: https://github.com/zph/tome/actions/runs/8114480337/job/22180215560

But oddly it's not failing on all architectures: https://github.com/zph/tome/actions/runs/8114480337/job/22180225385. ie Linux x86_64 succeeded: https://github.com/zph/tome/actions/runs/8114480337/job/22180214546.

**Comment by zph** [comment]
With backtrace:

```
❯ RUST_BACKTRACE=1 cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.05s
     Running unittests src/lib.rs (target/debug/deps/tome-ca586cb57dc09330)

running 29 tests
test commands::tests::test_should_not_source ... ok
test commands::tests::test_should_source ... ok
test commands::tests::test_help ... ok
test commands::tests::test_usage ... ok
test lib_tests::test_exec_simple_script ... ok
test lib_tests::test_exec_recursive_simple_script ... ok
test lib_tests::test_directory_completion ... ok
test lib_tests::test_script_directory_argument ... ok
test lib_tests::test_root_directory_completion ... ok
test lib_tests::test_script_in_directory ... ok
test lib_tests::test_simple_script ... ok
test lib_tests::test_dangerous_characters_quoted ... ok
test lib_tests::test_simple_script_no_completion ... ok
test lib_tests::test_simple_script_with_args ... ok
test lib_tests::test_script_in_directory_not_found ... ok
test lib_tests::test_tome_completion ... ok
test lib_tests::test_source ... ok
test shell_type_tests::test_shell_type::case_1_bash ... ok
test lib_tests::test_help_page ... ok
test shell_type_tests::test_shell_type::case_2_bin_bash ... ok
test lib_tests::test_execute_help ... ok
test shell_type_tests::test_shell_type::case_3_zsh ... ok
test lib_tests::test_help_page_when_execute_no_args ... ok
test lib_tests::test_use_arg ... ok
test lib_tests::test_execute_commands ... ok
test shell_type_tests::test_shell_type::case_4_bin_zsh ... ok
test shell_type_tests::test_shell_type::case_5_fish ... ok
test lib_tests::test_source_completion ... ok
test lib_tests::test_simple_script_completion ... FAILED

failures:

---- lib_tests::test_simple_script_completion stdout ----
thread 'lib_tests::test_simple_script_completion' panicked at 'assertion failed: `(left == right)`
  left: `Ok("")`,
 right: `Ok("file autocomplete example")`', src/lib_tests.rs:87:5
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /private/tmp/rust-20230816-6606-118f16e/rustc-1.71.1-src/library/core/src/panicking.rs:228:5
   4: tome::lib_tests::test_simple_script_completion
             at ./src/lib_tests.rs:87:5
   5: tome::lib_tests::test_simple_script_completion::{{closure}}
             at ./src/lib_tests.rs:86:36
   6: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20230816-6606-118f16e/rustc-1.71.1-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    lib_tests::test_simple_script_completion

test result: FAILED. 28 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```

**Comment by zph** [comment]
It's a platform issue w/ aarch64 on Mac (silicon) and Linux: https://github.com/zph/tome/actions/runs/8126166576/job/22209542959

**Comment by toumorokoshi** [comment]
I'll mark this as fixed as the CI is passing now - thanks!
